include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "*/android/**"
    - "*/ios/**"
    - "**/*.g.dart"
    - "lib/l10n/**"
    - "*.g.dart"
    - "*.freezed.dart"
    - "*.config.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    no_leading_underscores_for_library_prefixes: false
