include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "*/android/**"
    - "*/ios/**"
    - "**/*.g.dart"
    - "lib/l10n/**"
    - "*.g.dart"
    - "*.freezed.dart"
    - "*.config.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
    #sort_constructors_first:  true
    public_member_api_docs: false
    # prefer_relative_imports: true
    # todo обновить
    deprecated_consistency: false
